import { fetchFeedback } from '@/lib/api';
import { ProvLabel, ProvDot } from '@/components/shared/source-badge';

export default async function FeedbackPage() {
  const data = await fetchFeedback();

  return (
    <div className="max-w-[1360px] px-[clamp(16px,2.4vw,28px)] py-6 flex flex-col gap-8">

      <div className="flex flex-col gap-3.5">
        <div className="flex flex-col gap-1">
          <h1 className="m-0 text-[22px] font-semibold tracking-[-0.01em] leading-[1.2] text-[#DFE1E6]">Public Feedback</h1>
          <div className="flex flex-wrap items-center gap-2 text-[13.5px] text-[#7A8090]">
            <ProvLabel type="opinion" />
            <span className="text-[#4B5260]">·</span>
            <span>regulations.gov docket FTC-2023-0007</span>
          </div>
        </div>
        {data && (
          <div className="grid border-t border-b border-[#1C2028]" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(150px,1fr))' }}>
            {[
              { k: 'Sample analyzed', v: `${data._metadata.sample_size} comments` },
              { k: 'Total in docket', v: typeof data._metadata.total_comments_in_docket === 'number' ? `${data._metadata.total_comments_in_docket.toLocaleString()}+` : String(data._metadata.total_comments_in_docket) },
              { k: 'Classification', v: 'Machine, spot-checked' },
              { k: 'Generated by', v: data._metadata.deployment },
            ].map(({ k, v }) => (
              <div key={k} className="flex flex-col gap-[3px] py-[9px] pr-[14px]">
                <span className="text-[11px] text-[#4B5260]">{k}</span>
                <span className="font-mono text-[12px] text-[#C8CAD0]">{v}</span>
              </div>
            ))}
          </div>
        )}
      </div>

      {!data && (
        <div className="ds-panel flex items-start gap-[10px] p-4">
          <span className="text-[#C87070] mt-[1px]">!</span>
          <div>
            <div className="text-[14px] font-medium text-[#DFE1E6]">Comments analysis not available</div>
            <div className="mt-1 text-[13px] text-[#7A8090]">Run <code className="font-mono text-[12px]">python scripts/analyze_comments.py</code></div>
          </div>
        </div>
      )}

      {data && (
        <>
          <div className="ds-panel flex items-start gap-[10px] px-3 py-[10px] text-[13px] leading-[1.5] text-[#7A8090]">
            <span className="mt-[2px] shrink-0">i</span>
            <span><span className="font-medium text-[#DFE1E6]">Representativeness.</span> {data._metadata.sample_note || 'Commenters are self-selected; organized campaigns may be over-represented.'}</span>
          </div>

          <section className="flex flex-col gap-3">
            <div className="ds-section-head">
              <h2 className="m-0 text-[14px] font-semibold text-[#DFE1E6]">Summary</h2>
              <ProvLabel type="ai" />
            </div>
            <p className="m-0 max-w-[880px] text-[13.5px] leading-[1.65] text-[#C8CAD0]">{data.summary}</p>
          </section>

          <div className="grid gap-8" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,440px),1fr))' }}>

            {data.themes.length > 0 && (
              <section className="flex flex-col">
                <div className="ds-section-head">
                  <h2 className="m-0 text-[14px] font-semibold text-[#DFE1E6]">Themes</h2>
                  <ProvLabel type="ai" />
                </div>
                <div className="ds-row grid gap-3 py-2" style={{ gridTemplateColumns: '1fr 120px 52px 44px' }}>
                  <span className="text-[11px] font-medium uppercase tracking-[0.07em] text-[#4B5260]">Theme</span>
                  <span className="text-[11px] font-medium uppercase tracking-[0.07em] text-[#4B5260]">Share of sample</span>
                  <span className="text-[11px] font-medium uppercase tracking-[0.07em] text-[#4B5260] text-right">n</span>
                  <span className="text-[11px] font-medium uppercase tracking-[0.07em] text-[#4B5260] text-right">%</span>
                </div>
                {data.themes.map((t, i) => {
                  const pct = data._metadata.sample_size > 0 ? Math.round(t.comment_count / data._metadata.sample_size * 100) : 0;
                  const maxN = data.themes[0]?.comment_count || 1;
                  return (
                    <div key={i} className="ds-row grid gap-3 py-[9px] items-center hover:bg-[#131619]" style={{ gridTemplateColumns: '1fr 120px 52px 44px' }}>
                      <span className="text-[13.5px] text-[#C8CAD0]">{t.theme}</span>
                      <div className="h-1 bg-[#181C22]"><div className="h-full bg-[#4D8A72]" style={{ width: `${Math.round(t.comment_count / maxN * 100)}%` }} /></div>
                      <span className="font-mono text-[12px] text-[#7A8090] text-right">{t.comment_count.toLocaleString()}</span>
                      <span className="font-mono text-[12px] text-[#C8CAD0] text-right">{pct}%</span>
                    </div>
                  );
                })}
              </section>
            )}

            <div className="flex flex-col gap-7">
              {data.viewpoints.length > 0 && (
                <section className="flex flex-col gap-3">
                  <div className="ds-section-head">
                    <h2 className="m-0 text-[14px] font-semibold text-[#DFE1E6]">Viewpoints</h2>
                    <ProvLabel type="ai" />
                  </div>
                  {data.viewpoints.map((v, i) => {
                    const pct = data._metadata.sample_size > 0 ? Math.round(v.comment_count / data._metadata.sample_size * 100) : 0;
                    return (
                      <div key={i} className="ds-row grid gap-[10px] items-center py-[7px]" style={{ gridTemplateColumns: '150px 1fr 44px' }}>
                        <span className="text-[13.5px] text-[#C8CAD0]">{v.label}</span>
                        <span className="text-[13px] text-[#4B5260]">{v.description}</span>
                        <span className="font-mono text-[12px] text-right text-[#C8CAD0]">{pct}%</span>
                      </div>
                    );
                  })}
                </section>
              )}

              {/* Viewpoint distribution — visual summary of the analyzed 50-comment sample */}
              {data.viewpoints.length > 0 && (
                <section className="flex flex-col gap-3">
                  <div className="ds-section-head">
                    <h2 className="m-0 text-[14px] font-semibold text-[#DFE1E6]">Viewpoints in analyzed sample</h2>
                    <span className="text-[11px] text-[#4B5260]">{data._metadata.sample_size} comments analyzed from a {typeof data._metadata.total_comments_in_docket === 'number' ? data._metadata.total_comments_in_docket.toLocaleString() : String(data._metadata.total_comments_in_docket)}-comment docket</span>
                  </div>
                  <div className="flex flex-col gap-2.5">
                    {data.viewpoints.map((v, i) => {
                      const max = Math.max(...data.viewpoints.map(x => x.comment_count), 1);
                      const key = v.label.toLowerCase();
                      const color = key.includes('support') ? '#4D8A72' : key.includes('oppos') ? '#C87070' : '#8B7045';
                      return (
                        <div key={i} className="grid items-center gap-3" style={{ gridTemplateColumns: '110px 1fr 28px' }}>
                          <span className="text-[12.5px] text-[#C8CAD0] truncate">{v.label}</span>
                          <div className="h-2 bg-[#181C22]"><div className="h-full" style={{ width: `${Math.round(v.comment_count / max * 100)}%`, background: color }} /></div>
                          <span className="font-mono text-[12px] text-[#7A8090] text-right">{v.comment_count}</span>
                        </div>
                      );
                    })}
                  </div>
                </section>
              )}

              {data.affected_groups.length > 0 && (
                <section className="flex flex-col">
                  <div className="ds-section-head">
                    <h2 className="m-0 text-[14px] font-semibold text-[#DFE1E6]">Affected Groups</h2>
                    <span className="text-[11px] text-[#4B5260]">Self-identified mentions</span>
                  </div>
                  <div className="grid" style={{ gridTemplateColumns: '1fr 1fr', columnGap: 24 }}>
                    {data.affected_groups.map((g, i) => (
                      <div key={i} className="ds-row py-[7px] text-[13.5px] text-[#C8CAD0]">{g}</div>
                    ))}
                  </div>
                </section>
              )}
            </div>
          </div>

          {/* Evidence excerpts from themes */}
          {data.themes.some(t => t.evidence.length > 0) && (
            <section className="flex flex-col">
              <div className="ds-section-head">
                <h2 className="m-0 text-[14px] font-semibold text-[#DFE1E6]">Evidence <span className="text-[12px] font-normal text-[#4B5260]">Comment excerpts</span></h2>
              </div>
              {data.themes.flatMap(t => t.evidence.slice(0, 1)).slice(0, 4).map((ev, i) => (
                <div key={i} className="ds-row grid gap-[8px_24px] py-3" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,220px),1fr))' }}>
                  <div className="flex flex-col gap-[3px] text-[12px]">
                    <span className="font-mono text-[11px] text-[#4B5260]">{ev.comment_id}</span>
                    <span className="flex items-center gap-1.5 text-[#7A8090] mt-[2px]"><ProvDot type="opinion" /> Public Opinion</span>
                  </div>
                  <div className="text-[13.5px] leading-[1.6] text-[#DFE1E6]" style={{ gridColumn: 'span 2' }}>&ldquo;{ev.excerpt}&rdquo;</div>
                </div>
              ))}
            </section>
          )}

          {data.limitations.length > 0 && (
            <section className="flex flex-col">
              <div className="ds-section-head">
                <h2 className="m-0 text-[14px] font-semibold text-[#DFE1E6]">Analysis Limitations</h2>
                <ProvLabel type="ai" />
              </div>
              <div className="ds-panel">
                {data.limitations.map((l, i) => (
                  <div key={i} className="border-b border-[#181C22] px-[14px] py-[9px] last:border-0 text-[13px] leading-[1.5] text-[#7A8090]">{l}</div>
                ))}
              </div>
            </section>
          )}
        </>
      )}
    </div>
  );
}
