'use client';

import { useState } from 'react';
import { Loader2 } from 'lucide-react';

// ── Types ──────────────────────────────────────────────────────────────────

interface Stakeholder {
  group: string;
  description: string;
  impact_direction: 'positive' | 'negative' | 'mixed' | 'unclear';
}

interface AnalysisResult {
  summary: string;
  key_changes: string[];
  affected_stakeholders: Stakeholder[];
  potential_benefits: string[];
  potential_concerns: string[];
  implementation_questions: string[];
  areas_of_disagreement: string[];
  uncertainties: string[];
  disclaimer: string;
  _meta: {
    title: string;
    jurisdiction: string;
    policy_type: string;
    description: string;
    deployment: string;
    hypothetical: boolean;
  };
}

// ── Provenance marker for hypothetical output ─────────────────────────────

function HypoLabel({ className = '' }: { className?: string }) {
  return (
    <span className={`inline-flex items-center gap-[6px] text-[12.5px] text-[#6B65A8] ${className}`}>
      <span style={{ display:'inline-block', width:7, height:7, borderRadius:1, background:'transparent', border:'1px dashed #4F5FD4', flexShrink:0 }} />
      Hypothetical
    </span>
  );
}

function SectionHead({ title, right }: { title: string; right?: React.ReactNode }) {
  return (
    <div className="flex items-baseline justify-between gap-3 pb-2 border-b border-[#1C2028]">
      <h2 className="m-0 text-[14px] font-semibold text-[#DFE1E6]">{title}</h2>
      {right}
    </div>
  );
}

function BulletList({ items }: { items: string[] }) {
  return (
    <div className="flex flex-col">
      {items.map((item, i) => (
        <div key={i} className="grid gap-2 py-[6px] border-b border-[#181C22] last:border-0 text-[13.5px] leading-[1.5] text-[#DFE1E6]" style={{ gridTemplateColumns: '14px 1fr' }}>
          <span className="text-[#4B5260]">–</span>
          <span>{item}</span>
        </div>
      ))}
    </div>
  );
}

function ImpactBadge({ dir }: { dir: Stakeholder['impact_direction'] }) {
  const styles: Record<string, string> = {
    positive: 'bg-[rgba(77,138,114,.15)] text-[#4D8A72]',
    negative: 'bg-[rgba(200,112,112,.15)] text-[#C87070]',
    mixed:    'bg-[rgba(139,112,69,.15)] text-[#8B7045]',
    unclear:  'bg-[rgba(75,82,96,.2)] text-[#4B5260]',
  };
  return (
    <span className={`shrink-0 rounded-[2px] px-1.5 py-0.5 text-[12px] font-medium capitalize ${styles[dir] ?? styles.unclear}`}>
      {dir}
    </span>
  );
}

// ── Results ────────────────────────────────────────────────────────────────

function Results({ data, onEdit }: { data: AnalysisResult; onEdit: () => void }) {
  const bulletSections = [
    { title: 'Key Policy Changes',              items: data.key_changes },
    { title: 'Potential Benefits',              items: data.potential_benefits },
    { title: 'Potential Concerns',              items: data.potential_concerns },
    { title: 'Implementation Questions',        items: data.implementation_questions },
    { title: 'Areas of Potential Disagreement', items: data.areas_of_disagreement },
    { title: 'Uncertainties',                   items: data.uncertainties },
  ];

  return (
    <div className="flex flex-col gap-7">
      {/* Hypothetical banner */}
      <div className="flex items-start justify-between gap-4 flex-wrap rounded-[2px] px-4 py-3" style={{ border:'1px dashed #4F5FD4', background:'rgba(79,95,212,.05)' }}>
        <div className="flex items-start gap-3">
          <div>
            <div className="text-[14px] font-semibold text-[#DFE1E6]">AI-Generated Hypothetical Analysis</div>
            <div className="mt-0.5 text-[13px] leading-[1.5] text-[#7A8090]">
              Not public opinion, news reporting, or official policy language. Generated by {data._meta.deployment}.
            </div>
          </div>
        </div>
        <button onClick={onEdit} className="h-7 px-[10px] rounded-[2px] border border-[#1C2028] bg-[#0D0F12] text-[13px] text-[#DFE1E6] cursor-pointer hover:bg-[#131619] shrink-0">
          Edit input
        </button>
      </div>

      {/* Input summary */}
      <div className="rounded-[2px] border border-[#1C2028] bg-[#0D0F12] px-4 py-3 flex flex-col gap-1.5">
        <div className="flex flex-wrap gap-x-4 gap-y-1 text-[12.5px] text-[#4B5260]">
          <span>Title <span className="text-[#C8CAD0]">{data._meta.title}</span></span>
          <span>Jurisdiction <span className="text-[#C8CAD0]">{data._meta.jurisdiction}</span></span>
          <span>Type <span className="text-[#C8CAD0]">{data._meta.policy_type}</span></span>
        </div>
        <div className="text-[13px] text-[#7A8090] leading-[1.5]">Input: &ldquo;{data._meta.description}&rdquo;</div>
      </div>

      {/* Summary */}
      <section className="flex flex-col gap-3">
        <SectionHead title="Summary" right={<HypoLabel />} />
        <p className="m-0 max-w-[820px] text-[13.5px] leading-[1.65] text-[#C8CAD0]">{data.summary}</p>
      </section>

      {/* Stakeholders table */}
      {data.affected_stakeholders.length > 0 && (
        <section className="flex flex-col gap-3">
          <SectionHead title="Affected Stakeholders" right={<HypoLabel />} />
          <div className="overflow-x-auto">
            <div style={{ minWidth: 560 }}>
              <div className="grid gap-4 pb-2 border-b border-[#181C22]" style={{ gridTemplateColumns: '180px 1fr 90px' }}>
                <span className="text-[11px] font-medium uppercase tracking-[0.07em] text-[#4B5260]">Group</span>
                <span className="text-[11px] font-medium uppercase tracking-[0.07em] text-[#4B5260]">How they may be affected</span>
                <span className="text-[11px] font-medium uppercase tracking-[0.07em] text-[#4B5260]">Impact</span>
              </div>
              {data.affected_stakeholders.map((s, i) => (
                <div key={i} className="grid gap-4 py-[9px] border-b border-[#181C22] last:border-0 text-[13.5px] leading-[1.5] hover:bg-[#131619]" style={{ gridTemplateColumns: '180px 1fr 90px' }}>
                  <span className="font-medium text-[#DFE1E6]">{s.group}</span>
                  <span className="text-[#7A8090]">{s.description}</span>
                  <ImpactBadge dir={s.impact_direction} />
                </div>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* Bullet-list sections in 2-col grid */}
      <div className="grid gap-7" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,440px),1fr))' }}>
        {bulletSections.map(({ title, items }) =>
          items.length > 0 ? (
            <section key={title} className="flex flex-col gap-3">
              <SectionHead title={title} right={<HypoLabel />} />
              <BulletList items={items} />
            </section>
          ) : null
        )}
      </div>

      {/* Required evidence */}
      <section className="flex flex-col gap-3">
        <SectionHead title="Required Evidence" right={<span className="text-[12px] text-[#4B5260]">Real sources needed before drawing conclusions</span>} />
        <div className="grid gap-4 pb-2 border-b border-[#181C22]" style={{ gridTemplateColumns: 'minmax(0,1fr) 120px' }}>
          <span className="text-[11px] font-medium uppercase tracking-[0.07em] text-[#4B5260]">Evidence type</span>
          <span className="text-[11px] font-medium uppercase tracking-[0.07em] text-[#4B5260]">Status</span>
        </div>
        {[
          'Bill text or regulatory language with specific provisions',
          'Fiscal impact statement or cost-benefit analysis',
          'Demographic and economic data for affected jurisdiction',
          'Public comments or hearing testimony once introduced',
          'Reporting on comparable policies in similar jurisdictions',
        ].map((item, i) => (
          <div key={i} className="grid gap-4 py-[9px] border-b border-[#181C22] last:border-0 text-[13.5px]" style={{ gridTemplateColumns: 'minmax(0,1fr) 120px' }}>
            <span className="text-[#DFE1E6]">{item}</span>
            <span className="text-[12.5px] text-[#4B5260]">Not collected</span>
          </div>
        ))}
      </section>

      {/* Disclaimer */}
      <div className="font-mono text-[11px] leading-[1.5] text-[#4B5260] border-t border-[#1C2028] pt-3">
        {data.disclaimer}
      </div>
    </div>
  );
}

// ── Page ──────────────────────────────────────────────────────────────────

const JURISDICTIONS = ['Federal', 'Virginia', 'California', 'New York', 'Texas', 'Other state', 'Local'];
const POLICY_TYPES  = ['Legislation', 'Regulation', 'Executive Order', 'Local Ordinance', 'Other'];
const API_BASE      = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000';

export default function AnalyzePage() {
  const [title,        setTitle]        = useState('');
  const [description,  setDescription]  = useState('');
  const [jurisdiction, setJurisdiction] = useState('Federal');
  const [policyType,   setPolicyType]   = useState('Legislation');
  const [loading,      setLoading]      = useState(false);
  const [error,        setError]        = useState<string | null>(null);
  const [result,       setResult]       = useState<AnalysisResult | null>(null);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!title.trim() || !description.trim()) return;
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const res = await fetch(`${API_BASE}/api/analyze-policy`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title, description, jurisdiction, policy_type: policyType }),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error((body as { detail?: string }).detail ?? `Server error ${res.status}`);
      }
      setResult(await res.json() as AnalysisResult);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setLoading(false);
    }
  }

  const canSubmit = !loading && title.trim().length > 0 && description.trim().length > 0;

  if (result && !loading) {
    return (
      <div className="max-w-[1360px] px-[clamp(16px,2.4vw,28px)] py-6 flex flex-col gap-8">
        <div className="flex flex-col gap-1 pb-[14px] border-b border-[#1C2028]">
          <h1 className="m-0 text-[22px] font-semibold tracking-[-0.01em] leading-[1.2] text-[#DFE1E6]">Analyze a Policy</h1>
          <div className="text-[13.5px] text-[#7A8090]">Describe a proposed law or regulation and explore its potential impact.</div>
        </div>
        <Results data={result} onEdit={() => setResult(null)} />
      </div>
    );
  }

  return (
    <div className="max-w-[1360px] px-[clamp(16px,2.4vw,28px)] py-6 flex flex-col gap-8">
      <div className="flex flex-col gap-1 pb-[14px] border-b border-[#1C2028]">
        <h1 className="m-0 text-[22px] font-semibold tracking-[-0.01em] leading-[1.2] text-[#DFE1E6]">Analyze a Policy</h1>
        <div className="text-[13.5px] text-[#7A8090]">Describe a proposed law or regulation and explore its potential impact.</div>
      </div>

      <div className="grid gap-8 items-start" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,300px),1fr))' }}>

        {/* Form */}
        <form onSubmit={handleSubmit} className="col-span-2 min-w-0 flex flex-col gap-[18px]">

          <label className="flex flex-col gap-1.5">
            <span className="text-[13px] font-medium text-[#DFE1E6]">Policy Title</span>
            <input
              value={title}
              onChange={e => setTitle(e.target.value)}
              placeholder="e.g. Virginia Paid Family Leave Act"
              required
              className="h-9 rounded-[2px] border border-[#1C2028] bg-[#131619] px-[10px] text-[14px] text-[#DFE1E6] outline-none placeholder:text-[#4B5260] focus:border-[#4F5FD4]"
            />
          </label>

          <label className="flex flex-col gap-1.5">
            <div className="flex items-center justify-between">
              <span className="text-[13px] font-medium text-[#DFE1E6]">Policy Description</span>
              <span className="font-mono text-[11px] text-[#4B5260]">{description.length} / 2000</span>
            </div>
            <textarea
              value={description}
              onChange={e => setDescription(e.target.value.slice(0, 2000))}
              rows={8}
              required
              placeholder="Who the policy applies to, what it requires or prohibits, when it would take effect, and any known thresholds, funding mechanisms, or enforcement provisions."
              className="rounded-[2px] border border-[#1C2028] bg-[#131619] p-[10px] text-[14px] leading-[1.6] text-[#DFE1E6] outline-none resize-y placeholder:text-[#4B5260] focus:border-[#4F5FD4]"
            />
            <span className="text-[12.5px] text-[#4B5260]">Include thresholds, funding source, and enforcement where known.</span>
          </label>

          <div className="grid gap-[18px]" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(200px,1fr))' }}>
            <label className="flex flex-col gap-1.5">
              <span className="text-[13px] font-medium text-[#DFE1E6]">Jurisdiction</span>
              <div className="relative">
                <select
                  value={jurisdiction}
                  onChange={e => setJurisdiction(e.target.value)}
                  className="w-full h-9 appearance-none rounded-[2px] border border-[#1C2028] bg-[#131619] px-[10px] pr-8 text-[14px] text-[#DFE1E6] outline-none focus:border-[#4F5FD4]"
                >
                  {JURISDICTIONS.map(j => <option key={j}>{j}</option>)}
                </select>
                <span className="absolute right-[10px] top-[11px] text-[12px] text-[#4B5260] pointer-events-none">▾</span>
              </div>
            </label>

            <div className="flex flex-col gap-1.5">
              <span className="text-[13px] font-medium text-[#DFE1E6]">Policy Type</span>
              <div className="flex border border-[#1C2028] rounded-[2px] overflow-hidden">
                {POLICY_TYPES.map((t, i) => (
                  <button
                    key={t}
                    type="button"
                    onClick={() => setPolicyType(t)}
                    className="flex-1 h-[34px] text-[13px] cursor-pointer whitespace-nowrap transition-colors"
                    style={{
                      background: policyType === t ? '#1E2330' : 'transparent',
                      color: policyType === t ? '#DFE1E6' : '#7A8090',
                      border: 'none',
                      borderRight: i < POLICY_TYPES.length - 1 ? '1px solid #1C2028' : 'none',
                    }}
                  >
                    {t}
                  </button>
                ))}
              </div>
            </div>
          </div>

          <div className="flex items-center justify-between gap-3 flex-wrap pt-4 border-t border-[#1C2028]">
            <span className="text-[12.5px] text-[#4B5260]">Output is labeled as hypothetical and kept separate from policy evidence.</span>
            <button
              type="submit"
              disabled={!canSubmit}
              className="h-9 px-[18px] rounded-[2px] text-[14px] font-medium cursor-pointer disabled:cursor-not-allowed transition-colors"
              style={{
                background: canSubmit ? '#4F5FD4' : '#1A1E26',
                color: canSubmit ? '#fff' : '#4B5260',
                border: 'none',
              }}
            >
              {loading ? 'Analyzing…' : 'Analyze Policy'}
            </button>
          </div>
        </form>

        {/* Info sidebar */}
        <div className="flex flex-col gap-5">
          <div className="rounded-[2px] p-[14px] flex flex-col gap-2" style={{ border:'1px dashed #4F5FD4', background:'rgba(79,95,212,.05)' }}>
            <div className="text-[13px] font-semibold text-[#DFE1E6]">AI-Generated Hypothetical Analysis</div>
            <div className="text-[13px] leading-[1.55] text-[#7A8090]">
              Results are generated from your description only. They are not public comments, news reporting, or official policy language.
            </div>
          </div>
          <div className="flex flex-col">
            <div className="pb-1.5 border-b border-[#1C2028] text-[10.5px] font-semibold tracking-[.08em] text-[#4B5260]">OUTPUT SECTIONS</div>
            {['Summary','Key Policy Changes','Affected Stakeholders','Potential Benefits','Potential Concerns','Implementation Questions','Areas of Potential Disagreement','Uncertainties','Required Evidence'].map(s => (
              <div key={s} className="border-b border-[#181C22] py-[6px] text-[13px] text-[#7A8090]">{s}</div>
            ))}
          </div>
        </div>
      </div>

      {/* Loading */}
      {loading && (
        <div className="rounded-[2px] border border-[#1C2028] bg-[#131619] p-5 flex flex-col gap-3">
          <div className="flex items-center gap-2 text-[14px] font-semibold text-[#DFE1E6]">
            <Loader2 className="h-4 w-4 text-[#7A8090] animate-spin-slow" />
            Running analysis
          </div>
          <div className="font-mono text-[12.5px] text-[#7A8090]">{title} · {jurisdiction}</div>
          <div className="flex flex-col mt-1">
            {['Parsing policy description','Identifying affected groups','Mapping potential impacts','Listing implementation questions','Compiling evidence gaps'].map((step, i) => (
              <div key={i} className="flex items-center gap-2 py-[6px] border-t border-[#181C22] text-[13.5px] text-[#4B5260]">
                <span>–</span>{step}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Error */}
      {error && (
        <div className="flex items-start gap-[14px] rounded-[2px] p-4 max-w-[720px]" style={{ border:'1px solid rgba(200,112,112,.4)', background:'rgba(200,112,112,.05)' }}>
          <span className="text-[#C87070] mt-[1px] shrink-0">!</span>
          <div className="flex flex-col gap-1.5 flex-1">
            <div className="text-[14px] font-semibold text-[#DFE1E6]">Analysis could not be completed</div>
            <div className="text-[13.5px] text-[#7A8090] leading-[1.55]">{error}</div>
            <button onClick={() => setError(null)} className="self-start mt-1.5 h-[28px] px-3 rounded-[2px] border border-[#1C2028] bg-transparent text-[#DFE1E6] text-[13px] cursor-pointer hover:bg-[#131619]">Dismiss</button>
          </div>
        </div>
      )}
    </div>
  );
}
