import { fetchNews } from '@/lib/api';
import { ProvLabel } from '@/components/shared/source-badge';

export default async function NewsPage() {
  const data = await fetchNews();

  return (
    <div className="max-w-[1360px] px-[clamp(16px,2.4vw,28px)] py-6 flex flex-col gap-8">

      <div className="flex flex-col gap-3.5">
        <div className="flex flex-col gap-1">
          <h1 className="m-0 text-[22px] font-semibold tracking-[-0.01em] leading-[1.2] text-[#DFE1E6]">News Coverage</h1>
          <div className="flex flex-wrap items-center gap-2 text-[13.5px] text-[#7A8090]">
            <ProvLabel type="reporting" />
            <span className="text-[#4B5260]">·</span>
            <span>Curated corpus</span>
          </div>
        </div>
        {data && (
          <div className="grid border-t border-b border-[#1C2028]" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(150px,1fr))' }}>
            {[
              { k: 'Articles', v: String(data._metadata.articles_analyzed) },
              { k: 'Source note', v: data._metadata.source_note },
              { k: 'Generated by', v: data._metadata.deployment },
              { k: 'Date', v: new Date(data._metadata.generated_at).toLocaleDateString() },
            ].map(({ k, v }) => (
              <div key={k} className="flex flex-col gap-[3px] py-[9px] pr-[14px]">
                <span className="text-[11px] text-[#4B5260]">{k}</span>
                <span className="font-mono text-[12px] text-[#C8CAD0] truncate">{v}</span>
              </div>
            ))}
          </div>
        )}
      </div>

      {!data && (
        <div className="ds-panel flex items-start gap-[10px] p-4">
          <span className="text-[#C87070] mt-[1px]">!</span>
          <div>
            <div className="text-[14px] font-medium text-[#DFE1E6]">News analysis not available</div>
            <div className="mt-1 text-[13px] text-[#7A8090]">Run <code className="font-mono text-[12px]">python scripts/analyze_news.py</code></div>
          </div>
        </div>
      )}

      {data && (
        <>
          <div className="grid gap-8" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,420px),1fr))' }}>
            <div className="flex flex-col gap-5">
              <section className="flex flex-col gap-3">
                <div className="ds-section-head">
                  <h2 className="m-0 text-[14px] font-semibold text-[#DFE1E6]">Summary</h2>
                  <ProvLabel type="ai" />
                </div>
                <p className="m-0 text-[13.5px] leading-[1.65] text-[#C8CAD0]">{data.summary}</p>
              </section>

              {data.coverage_themes.length > 0 && (
                <section className="flex flex-col">
                  <div className="ds-section-head">
                    <h2 className="m-0 text-[14px] font-semibold text-[#DFE1E6]">Coverage Themes</h2>
                  </div>
                  {data.coverage_themes.map((t, i) => (
                    <div key={i} className="ds-row py-2 text-[13.5px] text-[#C8CAD0]">{t}</div>
                  ))}
                </section>
              )}
            </div>

            {data.key_developments.length > 0 && (
              <section className="flex flex-col">
                <div className="ds-section-head">
                  <h2 className="m-0 text-[14px] font-semibold text-[#DFE1E6]">Key Developments</h2>
                  <span className="text-[11px] text-[#4B5260]">As reported</span>
                </div>
                {data.key_developments.map((d, i) => (
                  <div key={i} className="ds-row py-[9px] text-[13.5px] leading-[1.5] text-[#C8CAD0]">{d}</div>
                ))}
              </section>
            )}
          </div>

          {data.articles.length > 0 && (
            <section className="flex flex-col">
              <div className="ds-section-head">
                <h2 className="m-0 text-[14px] font-semibold text-[#DFE1E6]">
                  Articles <span className="text-[12px] font-normal text-[#4B5260]">{data.articles.length} retrieved</span>
                </h2>
              </div>
              <div className="overflow-x-auto">
                <div style={{ minWidth: 760 }}>
                  <div className="ds-row grid gap-4 py-2" style={{ gridTemplateColumns: '96px 150px minmax(0,1fr) 100px 140px' }}>
                    <span className="text-[11px] font-medium uppercase tracking-[0.07em] text-[#4B5260]">Date</span>
                    <span className="text-[11px] font-medium uppercase tracking-[0.07em] text-[#4B5260]">Publication</span>
                    <span className="text-[11px] font-medium uppercase tracking-[0.07em] text-[#4B5260]">Article</span>
                    <span className="text-[11px] font-medium uppercase tracking-[0.07em] text-[#4B5260]">Format</span>
                    <span className="text-[11px] font-medium uppercase tracking-[0.07em] text-[#4B5260]">Provenance</span>
                  </div>
                  {data.articles.map((a, i) => {
                    const dateStr = a.date ? new Date(a.date).toLocaleDateString('en-US', { year: '2-digit', month: '2-digit', day: '2-digit' }) : '';
                    return (
                      <div key={i} className="ds-row grid gap-4 py-[11px] hover:bg-[#131619]" style={{ gridTemplateColumns: '96px 150px minmax(0,1fr) 100px 140px' }}>
                        <span className="font-mono text-[12px] text-[#6B7280] pt-[1px]">{dateStr}</span>
                        <span className="text-[13.5px] text-[#C8CAD0]">{a.publication}</span>
                        <div className="flex flex-col gap-[3px] min-w-0">
                          <span className="font-medium text-[13.5px] text-[#DFE1E6] leading-[1.4]">{a.headline}</span>
                          {a.summary && <span className="text-[13px] text-[#7A8090] leading-[1.5]">{a.summary}</span>}
                        </div>
                        <span className="text-[13px] text-[#7A8090]">{a.source_type}</span>
                        <ProvLabel type="reporting" />
                      </div>
                    );
                  })}
                </div>
              </div>
            </section>
          )}

          {data.limitations.length > 0 && (
            <section className="flex flex-col">
              <div className="ds-section-head">
                <h2 className="m-0 text-[14px] font-semibold text-[#DFE1E6]">Limitations</h2>
                <ProvLabel type="ai" />
              </div>
              <div className="ds-panel">
                {data.limitations.map((l, i) => (
                  <div key={i} className="border-b border-[#181C22] px-[14px] py-[9px] last:border-0 text-[13px] leading-[1.5] text-[#7A8090]">{l}</div>
                ))}
              </div>
            </section>
          )}
        </>
      )}
    </div>
  );
}
