import { fetchBriefing } from '@/lib/api';
import { ProvLabel, PROV } from '@/components/shared/source-badge';
import type { BriefingSource } from '@/types/api';

const TOC = ['Executive Summary','Policy Context','Key Policy Changes','Public Feedback','News Coverage','Stakeholders','Areas of Alignment','Areas of Difference','Uncertainties & Limitations','Sources'];

export default async function BriefingPage() {
  const data = await fetchBriefing();

  return (
    <div className="max-w-[1360px] px-[clamp(16px,2.4vw,28px)] py-6">
      <div className="flex gap-8 items-start">

        {/* TOC sidebar */}
        <aside className="hidden lg:flex w-[170px] shrink-0 flex-col sticky top-5 text-[13px]">
          <div className="pb-2 text-[10.5px] font-semibold tracking-[.08em] text-[#4B5260]">CONTENTS</div>
          {TOC.map((label, i) => (
            <a key={i} href={`#b${i}`} className="flex gap-2 border-t border-[#181C22] py-[5px] text-[#7A8090] no-underline hover:text-[#DFE1E6]">
              <span className="font-mono text-[11px] text-[#4B5260] w-[18px] shrink-0">{String(i+1).padStart(2,'0')}</span>
              {label}
            </a>
          ))}
        </aside>

        <article className="min-w-0 flex-1 max-w-[960px] flex flex-col">
          {/* Doc header */}
          <div className="flex flex-col gap-3 pb-4 border-b-2 border-[#DFE1E6]">
            <div className="flex justify-between gap-3 flex-wrap items-center">
              <span className="font-mono text-[11px] tracking-[.06em] text-[#7A8090]">FOR RESEARCH USE</span>
              <div className="flex gap-1.5">
                <button className="flex h-7 items-center gap-1.5 rounded-[2px] border border-[#1C2028] bg-transparent px-[10px] text-[12.5px] text-[#DFE1E6] cursor-pointer hover:bg-[#181D26]">PDF</button>
                <button className="flex h-7 items-center gap-1.5 rounded-[2px] border border-[#1C2028] bg-transparent px-[10px] text-[12.5px] text-[#DFE1E6] cursor-pointer hover:bg-[#181D26]">Share</button>
              </div>
            </div>
            <h1 className="m-0 text-[22px] font-semibold tracking-[-0.01em] leading-[1.2] text-[#DFE1E6]">Analyst Briefing</h1>
            <div className="text-[14px] text-[#C8CAD0]">FTC Non-Compete Clause Rule (16 CFR Part 910)</div>
          </div>

          {data && (
            <div className="grid border-b border-[#1C2028]" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(140px,1fr))' }}>
              {[
                { k: 'Prepared', v: new Date(data._metadata.generated_at).toLocaleDateString() },
                { k: 'Generated by', v: data._metadata.deployment },
                { k: 'Rule status', v: 'Set aside (vacated)' },
                { k: 'Evidence base', v: `${data._metadata.sources_used?.length ?? 3} source types` },
              ].map(({ k, v }) => (
                <div key={k} className="flex flex-col gap-[3px] py-[9px] pr-[14px]">
                  <span className="text-[11px] text-[#4B5260]">{k}</span>
                  <span className="font-mono text-[12px] text-[#C8CAD0]">{v}</span>
                </div>
              ))}
            </div>
          )}

          <div className="border-b border-[#1C2028] py-[9px] text-[13px] leading-[1.5] text-[#7A8090]">
            {data?._metadata.disclaimer ?? 'This briefing summarizes evidence as a research starting point. It does not recommend a policy position.'}
          </div>

          {!data && (
            <div className="ds-panel mt-6 flex items-start gap-[10px] p-4">
              <span className="text-[#C87070] mt-[1px]">!</span>
              <div>
                <div className="text-[14px] font-medium text-[#DFE1E6]">Briefing not available</div>
                <div className="mt-1 text-[13px] text-[#7A8090]">Run <code className="font-mono text-[12px]">python scripts/analyze_briefing.py</code></div>
              </div>
            </div>
          )}

          {data && (
            <>
              {[
                { id:'b0', n:'01', title:'Executive Summary',          prov:'ai'       as const, body: data.executive_summary,           bullets: null },
                { id:'b1', n:'02', title:'Policy Context',             prov:'official' as const, body: data.policy_context,               bullets: null },
                { id:'b2', n:'03', title:'Key Policy Changes',         prov:'official' as const, body: null,                              bullets: data.key_policy_changes },
                { id:'b3', n:'04', title:'Public Feedback',            prov:'opinion'  as const, body: data.public_feedback.summary,      bullets: data.public_feedback.themes },
                { id:'b4', n:'05', title:'News Coverage',              prov:'reporting'as const, body: data.news_coverage.summary,        bullets: data.news_coverage.developments },
              ].map(({ id, n, title, prov, body, bullets }) => (
                <section key={id} id={id} className="flex flex-col gap-[10px] border-b border-[#1C2028] py-5 scroll-mt-4">
                  <div className="flex items-baseline justify-between gap-3 flex-wrap">
                    <h2 className="m-0 text-[14px] font-semibold text-[#DFE1E6] flex items-baseline gap-[10px]">
                      <span className="font-mono text-[11px] font-normal text-[#4B5260]">{n}</span>{title}
                    </h2>
                    <ProvLabel type={prov} />
                  </div>
                  {body && <p className="m-0 text-[13.5px] leading-[1.7] text-[#C8CAD0]">{body}</p>}
                  {bullets && bullets.length > 0 && (
                    <div className="flex flex-col">
                      {bullets.map((b, i) => (
                        <div key={i} className="ds-row grid gap-2 py-[6px] text-[13.5px] leading-[1.5] text-[#DFE1E6]" style={{ gridTemplateColumns: '14px 1fr' }}>
                          <span className="text-[#4B5260]">–</span><span>{b}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </section>
              ))}

              {/* Stakeholders */}
              {data.stakeholders.length > 0 && (
                <section id="b5" className="flex flex-col gap-[10px] border-b border-[#1C2028] py-5 scroll-mt-4">
                  <div className="flex items-baseline justify-between gap-3">
                    <h2 className="m-0 text-[14px] font-semibold text-[#DFE1E6] flex items-baseline gap-[10px]"><span className="font-mono text-[11px] font-normal text-[#4B5260]">06</span>Stakeholders</h2>
                    <ProvLabel type="ai" />
                  </div>
                  {data.stakeholders.map((s, i) => (
                    <div key={i} className="ds-row flex items-start gap-3 py-3">
                      <span className={`shrink-0 rounded-[2px] px-1.5 py-0.5 text-[12px] font-medium capitalize mt-[1px] ${(s.impact||'').toLowerCase().includes('positive') ? 'bg-[rgba(77,138,114,.15)] text-[#4D8A72]' : (s.impact||'').toLowerCase().includes('negative') ? 'bg-[rgba(200,112,112,.15)] text-[#C87070]' : 'bg-[rgba(139,112,69,.15)] text-[#8B7045]'}`}>{s.impact||'mixed'}</span>
                      <div><div className="text-[13.5px] font-medium text-[#DFE1E6]">{s.group}</div><div className="mt-0.5 text-[13px] leading-[1.5] text-[#7A8090]">{s.description}</div></div>
                    </div>
                  ))}
                </section>
              )}

              {/* Alignment + Difference */}
              <div className="grid gap-8 border-b border-[#1C2028] py-5" style={{ gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,440px),1fr))' }}>
                {[
                  { id:'b6', n:'07', title:'Areas of Alignment',  items: data.areas_of_alignment },
                  { id:'b7', n:'08', title:'Areas of Difference', items: data.areas_of_difference },
                ].map(({ id, n, title, items }) => items.length > 0 && (
                  <section key={id} id={id} className="flex flex-col gap-[10px] scroll-mt-4">
                    <div className="flex items-baseline justify-between gap-3">
                      <h2 className="m-0 text-[14px] font-semibold text-[#DFE1E6] flex items-baseline gap-[10px]"><span className="font-mono text-[11px] font-normal text-[#4B5260]">{n}</span>{title}</h2>
                      <ProvLabel type="ai" />
                    </div>
                    {items.map((a, i) => (
                      <div key={i} className="ds-row grid gap-2 py-[6px] text-[13.5px] text-[#DFE1E6] leading-[1.5]" style={{ gridTemplateColumns: '14px 1fr' }}>
                        <span className="text-[#4B5260]">–</span><span>{a}</span>
                      </div>
                    ))}
                  </section>
                ))}
              </div>

              {/* Uncertainties */}
              {data.uncertainties_and_limitations.length > 0 && (
                <section id="b8" className="flex flex-col gap-[10px] border-b border-[#1C2028] py-5 scroll-mt-4">
                  <div className="flex items-baseline justify-between gap-3">
                    <h2 className="m-0 text-[14px] font-semibold text-[#DFE1E6] flex items-baseline gap-[10px]"><span className="font-mono text-[11px] font-normal text-[#4B5260]">09</span>Uncertainties &amp; Limitations</h2>
                    <ProvLabel type="ai" />
                  </div>
                  {data.uncertainties_and_limitations.map((u, i) => (
                    <div key={i} className="ds-row grid gap-2 py-[6px] text-[13.5px] text-[#DFE1E6] leading-[1.5]" style={{ gridTemplateColumns: '14px 1fr' }}>
                      <span className="text-[#4B5260]">–</span><span>{u}</span>
                    </div>
                  ))}
                </section>
              )}

              {/* Sources */}
              {data.sources.length > 0 && (
                <section id="b9" className="flex flex-col gap-[6px] pt-5 scroll-mt-4">
                  <h2 className="m-0 mb-1 text-[14px] font-semibold text-[#DFE1E6] flex gap-[10px] items-baseline">
                    <span className="font-mono text-[11px] font-normal text-[#4B5260]">10</span>Sources
                  </h2>
                  {data.sources.map((s: BriefingSource, i) => {
                    const provKey = s.type === 'official' ? 'official' : s.type === 'public_comment' ? 'opinion' : 'reporting';
                    const prov = PROV[provKey as keyof typeof PROV];
                    return (
                      <div key={i} className="ds-row grid gap-[10px] items-baseline py-[6px] text-[13px]" style={{ gridTemplateColumns: '32px minmax(0,1fr) auto' }}>
                        <span className="font-mono text-[12px] text-[#6B65A8]">[{i + 1}]</span>
                        <span className="min-w-0 text-[#DFE1E6]">{s.label} <span className="text-[#4B5260]">· {s.description}</span></span>
                        <span className="inline-flex items-center gap-[6px] text-[12px] text-[#8B97AF] whitespace-nowrap">
                          <span style={{ display:'inline-block', width:7, height:7, borderRadius:1, background: prov.fill, border:`1px solid ${prov.border}`, flexShrink:0 }} />
                          {prov.label}
                        </span>
                      </div>
                    );
                  })}
                </section>
              )}
            </>
          )}
        </article>
      </div>
    </div>
  );
}
